/**
 * Popular Ilishan-Remo landmarks sourced from Google Places (Nearby Search,
 * ranked by popularity) and filtered to the delivery area. Coordinates are
 * Google's; edit/deactivate individual entries from the admin console.
 *
 * Seed with:  npm run seed:landmarks
 */
export const GOOGLE_LANDMARKS_SEED = [
  {
    slug: 'babcock-university',
    name: 'Babcock University',
    area: 'Ilishan-Remo',
    description: 'University \u00b7 main campus, Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.718271, 6.89154] },
    isActive: true,
  },
  {
    slug: 'babcock-university-shopping-complex',
    name: 'Babcock University Shopping Complex',
    area: 'Ilishan-Remo',
    description: 'Shopping complex \u00b7 Babcock campus',
    geo: { type: 'Point' as const, coordinates: [3.720498, 6.891155] },
    isActive: true,
  },
  {
    slug: 'babcock-university-teaching-hospital',
    name: 'Babcock University Teaching Hospital (BUTH)',
    area: 'Ilishan-Remo',
    description: 'Teaching hospital \u00b7 Ikenne-Isara Rd',
    geo: { type: 'Point' as const, coordinates: [3.717291, 6.891086] },
    isActive: true,
  },
  {
    slug: 'babcock-university-medical-centre',
    name: 'Babcock University Medical Centre',
    area: 'Ilishan-Remo',
    description: 'Medical centre \u00b7 Babcock campus',
    geo: { type: 'Point' as const, coordinates: [3.710512, 6.893196] },
    isActive: true,
  },
  {
    slug: 'babcock-university-high-school',
    name: 'Babcock University High School',
    area: 'Ilishan-Remo',
    description: 'School \u00b7 Babcock campus',
    geo: { type: 'Point' as const, coordinates: [3.71849, 6.890261] },
    isActive: true,
  },
  {
    slug: 'pioneer-seventh-day-adventist-church',
    name: 'Pioneer Seventh-Day Adventist Church',
    area: 'Ilishan-Remo',
    description: 'Church \u00b7 Babcock campus',
    geo: { type: 'Point' as const, coordinates: [3.719714, 6.889718] },
    isActive: true,
  },
  {
    slug: 'ilisan-new-market',
    name: 'Ilisan New Market',
    area: 'Ilishan-Remo',
    description: 'Market \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.710512, 6.893157] },
    isActive: true,
  },
  {
    slug: 'nnpc-filling-station-ilisan',
    name: 'NNPC Filling Station',
    area: 'Ilishan-Remo',
    description: 'Filling station \u00b7 Benin-Sagamu Expressway',
    geo: { type: 'Point' as const, coordinates: [3.723934, 6.884094] },
    isActive: true,
  },
  {
    slug: 'total-filling-station-olofin',
    name: 'Total Filling Station (Olofin Rd)',
    area: 'Ilishan-Remo',
    description: 'Filling station \u00b7 Olofin Rd',
    geo: { type: 'Point' as const, coordinates: [3.709381, 6.893935] },
    isActive: true,
  },
  {
    slug: 'totalenergies-ilisan-service-station',
    name: 'TotalEnergies Ilisan Service Station',
    area: 'Ilishan-Remo',
    description: 'Filling station \u00b7 Sagamu-Ijebu Expressway',
    geo: { type: 'Point' as const, coordinates: [3.70023, 6.883873] },
    isActive: true,
  },
  {
    slug: 'exotic-oil-and-gas',
    name: 'Exotic Oil & Gas',
    area: 'Ilishan-Remo',
    description: 'Filling station \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.715161, 6.890735] },
    isActive: true,
  },
  {
    slug: 'greenville-lng-gas-station',
    name: 'Greenville LNG Gas Station',
    area: 'Ilishan-Remo',
    description: 'Gas station \u00b7 Ilisan II',
    geo: { type: 'Point' as const, coordinates: [3.725272, 6.882972] },
    isActive: true,
  },
  {
    slug: 'uba-babcock',
    name: 'UBA \u2014 Babcock',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Babcock area',
    geo: { type: 'Point' as const, coordinates: [3.721063, 6.890721] },
    isActive: true,
  },
  {
    slug: 'zenith-bank-babcock',
    name: 'Zenith Bank \u2014 Babcock',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Babcock area',
    geo: { type: 'Point' as const, coordinates: [3.72059, 6.890791] },
    isActive: true,
  },
  {
    slug: 'access-bank-babcock',
    name: 'Access Bank \u2014 Babcock',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Babcock Shopping Complex',
    geo: { type: 'Point' as const, coordinates: [3.720694, 6.890785] },
    isActive: true,
  },
  {
    slug: 'wema-bank-babcock',
    name: 'Wema Bank \u2014 Babcock',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Babcock area',
    geo: { type: 'Point' as const, coordinates: [3.720761, 6.890937] },
    isActive: true,
  },
  {
    slug: 'first-bank-babcock',
    name: 'First Bank \u2014 Babcock',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Babcock area',
    geo: { type: 'Point' as const, coordinates: [3.724193, 6.892343] },
    isActive: true,
  },
  {
    slug: 'ilisan-microfinance-bank',
    name: 'Ilisan Microfinance Bank',
    area: 'Ilishan-Remo',
    description: 'Bank \u00b7 Olofin Rd',
    geo: { type: 'Point' as const, coordinates: [3.709935, 6.89377] },
    isActive: true,
  },
  {
    slug: 'ilishan-central-mosque',
    name: 'Ilishan Central Mosque',
    area: 'Ilishan-Remo',
    description: 'Mosque \u00b7 town centre',
    geo: { type: 'Point' as const, coordinates: [3.71279, 6.892627] },
    isActive: true,
  },
  {
    slug: 'st-michael-catholic-church',
    name: 'St Michael Catholic Church',
    area: 'Ilishan-Remo',
    description: 'Catholic church \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.709033, 6.898532] },
    isActive: true,
  },
  {
    slug: 'st-barnabas-anglican-church',
    name: 'St Barnabas Anglican Church',
    area: 'Ilishan-Remo',
    description: 'Anglican church \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.708316, 6.896156] },
    isActive: true,
  },
  {
    slug: 'royal-cream-suites-hotel',
    name: 'Royal Cream Suites Hotel',
    area: 'Ilishan-Remo',
    description: 'Hotel \u00b7 Olofin Rd',
    geo: { type: 'Point' as const, coordinates: [3.707912, 6.895841] },
    isActive: true,
  },
  {
    slug: 'havillah-cottage-and-lounge',
    name: 'Havillah Cottage & Lounge',
    area: 'Ilishan-Remo',
    description: 'Hotel \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.704355, 6.890148] },
    isActive: true,
  },
  {
    slug: 'memorable-hotels',
    name: 'Memorable Hotels',
    area: 'Ilishan-Remo',
    description: 'Hotel \u00b7 Olubajo St',
    geo: { type: 'Point' as const, coordinates: [3.709626, 6.878354] },
    isActive: true,
  },
  {
    slug: 'four-city-hotel-and-lounge',
    name: 'Four City Hotel & Lounge',
    area: 'Ilishan-Remo',
    description: 'Hotel \u00b7 Ilishan-Remo',
    geo: { type: 'Point' as const, coordinates: [3.719222, 6.902661] },
    isActive: true,
  },
  {
    slug: 'ilisan-primary-health-centre',
    name: 'Ilisan Primary Health Centre',
    area: 'Ilishan-Remo',
    description: 'Health centre \u00b7 Olofin Rd',
    geo: { type: 'Point' as const, coordinates: [3.709031, 6.894851] },
    isActive: true,
  },
  {
    slug: 'shalom-medical-centre',
    name: 'Shalom Medical Centre',
    area: 'Ilishan-Remo',
    description: 'Clinic \u00b7 Olofin St, Dudu roundabout',
    geo: { type: 'Point' as const, coordinates: [3.71093, 6.892552] },
    isActive: true,
  },
];
